[유하람] SMS인증 구현, 회원가입, 로그인, 데코레이터 구현
wecode-bootcamp-korea/15-2nd-kiwiMarket-backend pull request #2
Opened 2020-12-30 16:53 UTC by haileeCoder

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- SMS인증, 회원가입, 로그인, 데코레이터 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 네이버 문자인증 API를 사용한 SMS인증 기능 구현, 
- 회원가입, 로그인 기능 구현
- 데코레이터 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-04 01:50 UTC, jamessoun93 requested changes
- 하람님 여러가지 많이 리서치도 하시면서 적용해보신 흔적이 많아서 보기가 좋네요! 
- 다만, 여러가지 기능을 한번에 구현하시다보니 조금 급하게 짠 것 같은 코드들이 많이 보이네요. 
- 리뷰내용 반영하시면서 한줄한줄 어떻게 더 효율적으로 리팩토링할 수 있을지 고민해보세요.
- 그리고 `.DS_Store` 전부 없애주세요!

2021-01-04 01:50 UTC, jamessoun93 commented on user/models.py
> +    address3    = models.CharField(max_length=20, null=False)
여기서는 컬럼명만 보고 해당 컬럼들에 정확하게 주소의 어떤 부분들이 들어가야하는지 파악하기 어렵습니다. 주소의 어떤 부분들을 구분하기 위해서 컬럼을 나누셨는지 명확하게 표현해주세요.

2021-01-04 01:50 UTC, jamessoun93 commented on user/tests.py
> +from my_settings import (service_id, secretKey, AUTH_ACCESS_KEY, AUTH_SECRET_KEY, SMS_SEND_PHONE_NUMBER, SECRET_KEY, ALGORITHM)
```suggestion
from my_settings import (
    service_id, 
    secretKey, 
    AUTH_ACCESS_KEY, 
    AUTH_SECRET_KEY, 
    SMS_SEND_PHONE_NUMBER, 
    SECRET_KEY, 
    ALGORITHM
)
```

2021-01-04 01:50 UTC, jamessoun93 commented on user/tests.py
> +            updated_at=datetime.datetime.now(),
`auto_now_add` 와 `auto_now` 가 있다면 자동생성 필드여서 값을 넣어주실 필요가 없습니다.

2021-01-04 01:50 UTC, jamessoun93 commented on user/utils.py
> +    return wrapper
- 똑같은 로직인데 코드만 조금 다른 데코레이터 두개가 함께 올라와있네요.
- 그리고 파이썬에서는 `None` 을 `==` 로 비교하지 않습니다. `None` 은 값이 없음을 뜻하니 비교 자체가 불가능하죠. `is` 를 사용해주세요.

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +from django.core.exceptions     import ValidationError
사용하지 않는 것들은 불필요하게 import 해주시지 말고 없애주세요~

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +        return token
토큰 존재여부는 이미 만들어놓으신 `decorator` 를 통해 확인이 가능하므로 이 부분은 필요가 없어보입니다.

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +            )
여기서는 `transaction`에 대해 알아보신 후 적용해보시면 좋을 것 같습니다.

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +        except ValidationError:
이 `POST` 요청에서 어떤 부분에서 `ValidationError`가 발생하나요?

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +            )
여기도 transaction 활용해주세요 :)

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +            } for address in FullAddress.objects.select_related('full_address').filter(user_id = request.user.id)]
print 문 없애주시고 select_related 의 결과물을 변수에 할당해 사용해주시면 훨씬 깔끔해지겠네요.

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +        except ValidationError:
이 로직은 decorator 에서 처리해줘야하는 로직입니다. 로직의 분리를 위해 데코레이터에 인증 관련한 기능을 모아둔건데 정작 에러는 여기서 잡아줄 이유가 없겠죠?

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +            } for near_address in Address.objects.filter(code__startswith=address_code)]
여기도 위 리뷰내용과 같습니다.

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +                created_at        = datetime.datetime.now()
`auto_now_add=True` 가 있기때문에 굳이 현재 시간을 함께 넣어주실 필요가 없습니다.

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +            address_data = FullAddress.objects.select_related('full_address').filter(user_id=request.user.id).first()
여기서 `select_related` 를 사용하면 어떤 효과가 있을까요?

2021-01-04 01:50 UTC, jamessoun93 commented on user/views.py
> +class SalesHistoryView(View):
판매내역 및 주문 관련한 view 는 따로 app 으로 분리해주시는게 관리하기 편하실거라 생각해요.

2021-01-04 16:42 UTC, haileeCoder commented on user/models.py
> +    address3    = models.CharField(max_length=20, null=False)
region, district, neighborhood으로 수정했습니다!

2021-01-04 16:43 UTC, haileeCoder commented on user/tests.py
> +from my_settings import (service_id, secretKey, AUTH_ACCESS_KEY, AUTH_SECRET_KEY, SMS_SEND_PHONE_NUMBER, SECRET_KEY, ALGORITHM)
반영했습니다!

2021-01-04 16:43 UTC, haileeCoder commented on user/tests.py
> +            updated_at=datetime.datetime.now(),
ㅎㅎ넵 모델 확인 후 해당 부분 삭제하였습니다!

2021-01-04 17:00 UTC, haileeCoder commented on user/utils.py
> +    return wrapper
반영했습니다

2021-01-04 17:03 UTC, haileeCoder commented on user/views.py
> +from django.core.exceptions     import ValidationError
반영했습니다~

2021-01-04 17:06 UTC, haileeCoder commented on user/views.py
> +        return token
초반 커밋 이후 삭제된 메서드입니다! 
우선 다른 사항들 반영하고 커밋하도록 하겠습니다!

2021-01-04 17:12 UTC, haileeCoder commented on user/views.py
> +            )
transaction 적용 후 
IntegrityError 예외처리로 handle_exception()하도록 반영하였습니다.

2021-01-04 17:13 UTC, haileeCoder commented on user/views.py
> +        except ValidationError:
해당부분 삭제하였습니다!

2021-01-04 17:22 UTC, haileeCoder commented on user/views.py
> +            )
transaction 적용 후 예외처리 적용하였습니다!

2021-01-04 17:37 UTC, haileeCoder commented on user/views.py
> +            } for address in FullAddress.objects.select_related('full_address').filter(user_id = request.user.id)]
반영하였습니다!

2021-01-04 17:38 UTC, haileeCoder commented on user/views.py
> +        except ValidationError:
반영했습니다!

2021-01-04 17:39 UTC, haileeCoder commented on user/views.py
> +                created_at        = datetime.datetime.now()
해당 로직 삭제하였습니다.

2021-01-04 17:56 UTC, haileeCoder commented on user/views.py
> +            address_data = FullAddress.objects.select_related('full_address').filter(user_id=request.user.id).first()
참조, 역참조 공부해보고자 최대한 모든상황에서 select_related()를 사용하는 방식으로 작성했는데 현재 상황은 불필요한 방법일까요..? 
fulladdresses테이블에서 해당 유저가 가지고있는 주소를 찾기위해 addresses테이블을 역참조하여 주소를 가져오고자 했습니다🥺

2021-01-04 18:02 UTC, haileeCoder commented on user/views.py
> +class SalesHistoryView(View):
키위마켓에서 판매부분은 user의 속성에 가깝다고 생각해서 이렇게 해뒀는데 분리하는 방향에 대해서도 이야기해보도록 하겠습니다.
내일 팀원들과 상의해서 반영하도록 하겠습니다!!

2021-01-05 06:49 UTC, soheon-lee commented on user/models.py
> +    deleted_at              = models.DateTimeField(null = True)
코드 간격 정렬해주세요~

2021-01-05 06:49 UTC, soheon-lee commented on user/views.py
> +        # base64로 인코딩해서 signingKey 생성
하람님 사용하지 않는 메모용 주석은 제거해주세요 :)
주석은 코드 자체만으로는 개발자가 이해하기 어려울 경우에 사용하는데, 현재 코드는 흐름을 잘 작성하셔서 이해하는데에 큰 어려움이 없기 때문에 주석이 꼭 필요한 것 같지 않습니다

2021-01-05 06:49 UTC, soheon-lee commented on user/views.py
> +        # base64로 인코딩해서 signingKey 생성
아래 쭉 내려가면서 메모용 주석은 모두 제거해주세요

2021-01-05 06:49 UTC, soheon-lee commented on user/views.py
> +            #     return JsonResponse({'message': 'DUPLICATED_EMAIL'}, status=409)
사용하지 않는 주석은 제거해주세요

2021-01-05 06:49 UTC, soheon-lee commented on user/views.py
> +            token = jwt.encode({'id':User.objects.latest('id').id}, SECRET_KEY, ALGORITHM)
가장 최근에 생성된 유저의 id를 담으시는 군요! :) 이 방법도 좋지만, 내가 방금 생성한 id가 가장 최근에 생성된 id라는 보장이 어려울 수도 있습니다 하람님
따라서, 179번 줄에서 create하는 User 객체를 특정한 변수에 담아서, 그 변수의 id를 token에 삽입하시는 방법을 추천드립니다 :)

2021-01-05 06:49 UTC, soheon-lee commented on user/urls.py
> +    path('/deletemyaddress', DeleteMyAddressView.as_view()),
myaddress를 다루는 url에 add 와 delete 라는 동사가 포함되어 있는 것이 RESTful API에 적합하지 않은 것 같다고 판단됩니다.

AddressView에 두 엔드포인트를 합치시고, delete뷰에 있는 post 메소드를 `delete`메소드로 변경해보는 것을 추천드립니다.

2021-01-05 06:49 UTC, soheon-lee commented on user/views.py
> +
아까 RESTful API 주소에 대한 언급은 해당 두 View에 대한 코멘트였습니다 :)

2021-01-05 06:49 UTC, soheon-lee commented on user/views.py
> +
깔끔한 코드를 위해 불필요한 주석 및 공백은 제거해주세요

2021-01-05 06:49 UTC, soheon-lee commented on user/views.py
> +            return JsonResponse({'message' : 'PRODUCT_DOES_NOT_EXIST'}, status = 404)
꼼꼼한 에러처리 goood!

2021-01-05 10:40 UTC, haileeCoder commented on user/models.py
> +    deleted_at              = models.DateTimeField(null = True)
수정하였습니다~

2021-01-05 18:41 UTC, haileeCoder commented on user/views.py
> +        # base64로 인코딩해서 signingKey 생성
제거하였습니다.

2021-01-05 18:42 UTC, haileeCoder commented on user/views.py
> +            #     return JsonResponse({'message': 'DUPLICATED_EMAIL'}, status=409)
제거하였습니다.

2021-01-05 18:53 UTC, haileeCoder commented on user/views.py
> +            token = jwt.encode({'id':User.objects.latest('id').id}, SECRET_KEY, ALGORITHM)
create한 객체를 user 변수에 담아서 FullAddress 객체 생성, 토큰 발행 시에 활용했습니다.

2021-01-05 19:02 UTC, haileeCoder commented on user/urls.py
> +    path('/deletemyaddress', DeleteMyAddressView.as_view()),
수정하였습니다~

2021-01-05 19:03 UTC, haileeCoder commented on user/views.py
> +
수정하였습니다~

2021-01-05 19:03 UTC, haileeCoder commented on user/views.py
> +
반영하였습니다!

2021-01-05 19:03 UTC, haileeCoder commented on user/views.py
> +            return JsonResponse({'message' : 'PRODUCT_DOES_NOT_EXIST'}, status = 404)
🥺🥺🥺🥺🥺💕💕💕💕💕💕

2021-01-06 10:46 UTC, soheon-lee commented on user/urls.py
> +    path('/profile', UserProfileView.as_view()),
`selectmyaddress`와 `myaddress`도 분리될 resource가 아니라고 판단됩니다.
Select의 get method가 MyAddressView에 포함되는 것이 RESTful API에 걸맞겠네요 :)

2021-01-06 10:46 UTC, soheon-lee commented on user/views.py
> +
깔끔한 코드를 위해 공백은 필요한 만큼만 넣어주세요 :)

2021-01-06 10:46 UTC, soheon-lee commented on user/views.py
> +            return JsonResponse({'message': 'INVALID_USER'}, status=400)
이 validation error는 어떤 경우에 발생하는 에러를 잡으신건가요?

2021-01-06 10:48 UTC, haileeCoder commented on user/views.py
> +
삭제하였습니다~

2021-01-06 10:49 UTC, haileeCoder commented on user/views.py
> +            return JsonResponse({'message': 'INVALID_USER'}, status=400)
로그인 토큰에서 이미 예외처리를 했기 때문에 
해당 예외처리가 적힌 부분 모두 삭제했습니다!

2021-01-06 10:56 UTC, haileeCoder commented on user/urls.py
> +    path('/profile', UserProfileView.as_view()),
GET, POST, DELETE 메서드로 구성된 하나의 클래스로 수정하였습니다!

2021-01-07 02:33 UTC, lordmyshepherd requested changes

2021-01-07 02:33 UTC, lordmyshepherd commented on user/views.py
> +        return HttpResponse(res.status_code)
👍

2021-01-07 02:33 UTC, lordmyshepherd commented on product/models.py
> +    image_url  = models.ImageField(upload_to=user_directory_path,null=True,blank=True)
하람님 상품 이지미를 host os에 저장하는 이유가 있나요?

2021-01-07 02:52 UTC, lordmyshepherd approved these changes

2021-01-07 02:52 UTC, lordmyshepherd commented on user/views.py
> +            } for item in Product.objects.filter(uploader_id=request.user.id, order_status_id=order_status_id)]
수정해주세요~

2021-01-07 02:54 UTC, lordmyshepherd commented on user/views.py
> +            } for item in Product.objects.filter(uploader_id=request.user.id, order_status_id=order_status_id)]
zoom에서 말씀드린데로 수정 부탁드려요~

2021-01-07 06:41 UTC, haileeCoder commented on user/views.py
> +        return HttpResponse(res.status_code)
🌟🌟🌟🤩🙌🏻🌟

2021-01-07 06:42 UTC, haileeCoder commented on user/views.py
> +            } for item in Product.objects.filter(uploader_id=request.user.id, order_status_id=order_status_id)]
반영했습니다~

2021-01-07 15:14 UTC, merged